version: '3.8'

services:
  db:
    image: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - type: volume
        source: dbprod
        target: /data/db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    depends_on:
      - api
    restart: unless-stopped

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    depends_on:
      - db
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - MONGO_USERNAME
      - MONGO_PWD


  reverse-proxy:
    build:
      context: ./reverse-proxy
      dockerfile: Dockerfile.prod
    depends_on:
      - db
      - api
      - client
    restart: unless-stopped
    expose:
      - 80
    ports:
      - 80:80

volumes:
  dbprod:
    external: true