version: '3.8'

services:
  db:
    image: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - type: volume
        source: dbprod
        target: /data/db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    depends_on:
      - api
    restart: unless-stopped

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    depends_on:
      - db
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - MONGO_USERNAME
      - MONGO_PWD


  reverse-proxy:
    build:
      context: ./reverse-proxy
      dockerfile: Dockerfile.prod
    depends_on:
      - db
      - api
      - client
    restart: unless-stopped
    expose:
      - 80
      - 443
    ports:
      - 80:80
      - 443:443
    volumes:
      # For SSL certificates, they must be in /etc/letsencrypt/live/docker-test
      # This path can be changed in the `prod.conf` file within the `reverse-proxy/conf` directory (e.g. **/*/www.my-website.com/*.pem).
      # Do not forget to change the starting path below too in order to have the same both here and in the `.conf`.
      - type: bind
        source: /etc/letsencrypt
        target: /etc/letsencrypt

volumes:
  dbprod:
    external: true
